# Generated by Django 4.2.25 on 2025-10-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('CARTEIRA', 'Carteira'), ('CC', 'Conta Corrente'), ('POUPANCA', 'Poupança'), ('CREDITO', 'Cartão de Crédito'), ('INVEST', 'Investimento'), ('OUTRO', 'Outro')], default='CC', max_length=14, verbose_name='Tipo de Conta'),
        ),
    ]
